export { IResponse } from '@common/interfaces/response.interface'
export { ITechnology } from '@common/interfaces/tech.interface'
export { IHandler } from '@common/interfaces/handler.interface'
export { ICourse } from '@common/interfaces/course.interface'
export { IModel } from '@common/interfaces/model.interface'
export { ITask } from '@common/interfaces/task.interface'
export { INote } from '@common/interfaces/note.interface'
export { IFile } from '@common/interfaces/file.interface'