export { ITechnology } from './tech.interface'
export { IHandler } from './handler.interface'
export { ICourse } from './course.interface'
export { IModel } from './model.interface'
export { ITask } from './task.interface'
export { IResponse } from './response.interface'